### ISSUE TITLE
hi im getting this error and idk how to fix it.

### ISSUE THREAD

**Issue by kpopdev** [brandons209/Script-Generator-Cog#13] opened 2020-12-27 06:49 UTC
[17:54:50] ERROR    Exception in command 'confess'                                                                [red]
                    ┌──────────────────────────── Traceback (most recent call last) ────────────────────────────┐
                    │ C:\Users\Administrator\redenv\lib\site-packages\discord\ext\commands\core.py:85 in        │
                    │ wrapped                                                                                   │
                    │                                                                                           │
                    │     82 │   @functools.wraps(coro)                                                         │
                    │     83 │   async def wrapped(*args, **kwargs):                                            │
                    │     84 │   │   try:                                                                       │
                    │ ❱   85 │   │   │   ret = await coro(*args, **kwargs)                                      │
                    │     86 │   │   except CommandError:                                                       │
                    │     87 │   │   │   ctx.command_failed = True                                              │
                    │     88 │   │   │   raise                                                                  │
                    │                                                                                           │
                    │ C:\Users\Administrator\AppData\Local\Red-DiscordBot\Red-DiscordBot\data\candy\cogs\CogMan │
                    │ ager\cogs\confession\confession.py:144 in confess                                         │
                    │                                                                                           │
                    │   141 │   │   │   │   embed.description = guild.name                                      │
                    │   142 │   │   │   │   embeds.append(embed)                                                │
                    │   143 │   │   │                                                                           │
                    │ ❱ 144 │   │   │   await menu(ctx, pages=embeds, controls=SELECT_CONTROLS, message=None,   │
                    │       page=0, timeout=20)                                                                 │
                    │   145 │                                                                                   │
                    │   146 │   async def selected_guild(self, ctx, user_guilds, confession, page):             │
                    │   147 │   │                                                                               │
                    │                                                                                           │
                    │ C:\Users\Administrator\redenv\lib\site-packages\redbot\core\utils\menus.py:59 in menu     │
                    │                                                                                           │
                    │    56 │   RuntimeError                                                                    │
                    │    57 │   │   If either of the notes above are violated                                   │
                    │    58 │   """                                                                             │
                    │ ❱  59 │   if not isinstance(pages[0], (discord.Embed, str)):                              │
                    │    60 │   │   raise RuntimeError("Pages must be of type discord.Embed or str")            │
                    │    61 │   if not all(isinstance(x, discord.Embed) for x in pages) and not all(            │
                    │    62 │   │   isinstance(x, str) for x in pages                                           │
                    └───────────────────────────────────────────────────────────────────────────────────────────┘
                    IndexError: list index out of range

**Comment by brandons209** [comment] 2020-12-27 10:05
Hmm. not sure, it seems like when the menu is created there is no pages even though they should be there. Is the confession room setup in each guild the bot is apart of?

**Comment by kpopdev** [comment] 2020-12-27 12:14
it only setup for my server
there is no more people.

**Comment by kpopdev** [comment] 2020-12-27 12:14
i mean only my server not other servers.

**Comment by brandons209** [comment] 2020-12-27 12:40
Then I am really confused. If thats the case then it is somehow running code that shouldn't be possible in that state. You can try uninstalling and reinstalling the cog to be safe. Also make sure you have the intents turned on for your bot as per redbot setup guide.

**Comment by kpopdev** [comment] 2020-12-27 12:53
if i dont turn on intents the bot wont even run.but i will reinstall it thank you.

**Comment by brandons209** [comment] 2021-01-06 05:44
Is it working now? If it is I can close this issue.

**Comment by kpopdev** [comment] 2021-01-06 08:59
how its working when u didnt even fix it? its spamming my console everyday.
[21:12:11] ERROR    Exception in command 'confess'                                                                [red]
                    ┌──────────────────────────── Traceback (most recent call last) ────────────────────────────┐
                    │ C:\Users\Administrator\redenv\lib\site-packages\discord\ext\commands\core.py:85 in        │
                    │ wrapped                                                                                   │
                    │                                                                                           │
                    │     82 │   @functools.wraps(coro)                                                         │
                    │     83 │   async def wrapped(*args, **kwargs):                                            │
                    │     84 │   │   try:                                                                       │
                    │ ❱   85 │   │   │   ret = await coro(*args, **kwargs)                                      │
                    │     86 │   │   except CommandError:                                                       │
                    │     87 │   │   │   ctx.command_failed = True                                              │
                    │     88 │   │   │   raise                                                                  │
                    │                                                                                           │
                    │ C:\Users\Administrator\AppData\Local\Red-DiscordBot\Red-DiscordBot\data\candy\cogs\CogMan │
                    │ ager\cogs\confession\confession.py:144 in confess                                         │
                    │                                                                                           │
                    │   141 │   │   │   │   embed.description = guild.name                                      │
                    │   142 │   │   │   │   embeds.append(embed)                                                │
                    │   143 │   │   │                                                                           │
                    │ ❱ 144 │   │   │   await menu(ctx, pages=embeds, controls=SELECT_CONTROLS, message=None,   │
                    │       page=0, timeout=20)                                                                 │
                    │   145 │                                                                                   │
                    │   146 │   async def selected_guild(self, ctx, user_guilds, confession, page):             │
                    │   147 │   │                                                                               │
                    │                                                                                           │
                    │ C:\Users\Administrator\redenv\lib\site-packages\redbot\core\utils\menus.py:59 in menu     │
                    │                                                                                           │
                    │    56 │   RuntimeError                                                                    │
                    │    57 │   │   If either of the notes above are violated                                   │
                    │    58 │   """                                                                             │
                    │ ❱  59 │   if not isinstance(pages[0], (discord.Embed, str)):                              │
                    │    60 │   │   raise RuntimeError("Pages must be of type discord.Embed or str")            │
                    │    61 │   if not all(isinstance(x, discord.Embed) for x in pages) and not all(            │
                    │    62 │   │   isinstance(x, str) for x in pages                                           │
                    └───────────────────────────────────────────────────────────────────────────────────────────┘
                    IndexError: list index out of range


[15:27:27] ERROR    Exception in command 'confess'                                                                [red]
                    ┌──────────────────────────── Traceback (most recent call last) ────────────────────────────┐
                    │ C:\Users\Administrator\redenv\lib\site-packages\discord\ext\commands\core.py:85 in        │
                    │ wrapped                                                                                   │
                    │                                                                                           │
                    │     82 │   @functools.wraps(coro)                                                         │
                    │     83 │   async def wrapped(*args, **kwargs):                                            │
                    │     84 │   │   try:                                                                       │
                    │ ❱   85 │   │   │   ret = await coro(*args, **kwargs)                                      │
                    │     86 │   │   except CommandError:                                                       │
                    │     87 │   │   │   ctx.command_failed = True                                              │
                    │     88 │   │   │   raise                                                                  │
                    │                                                                                           │
                    │ C:\Users\Administrator\AppData\Local\Red-DiscordBot\Red-DiscordBot\data\candy\cogs\CogMan │
                    │ ager\cogs\confession\confession.py:144 in confess                                         │
                    │                                                                                           │
                    │   141 │   │   │   │   embed.description = guild.name                                      │
                    │   142 │   │   │   │   embeds.append(embed)                                                │
                    │   143 │   │   │                                                                           │
                    │ ❱ 144 │   │   │   await menu(ctx, pages=embeds, controls=SELECT_CONTROLS, message=None,   │
                    │       page=0, timeout=20)                                                                 │
                    │   145 │                                                                                   │
                    │   146 │   async def selected_guild(self, ctx, user_guilds, confession, page):             │
                    │   147 │   │                                                                               │
                    │                                                                                           │
                    │ C:\Users\Administrator\redenv\lib\site-packages\redbot\core\utils\menus.py:59 in menu     │
                    │                                                                                           │
                    │    56 │   RuntimeError                                                                    │
                    │    57 │   │   If either of the notes above are violated                                   │
                    │    58 │   """                                                                             │
                    │ ❱  59 │   if not isinstance(pages[0], (discord.Embed, str)):                              │
                    │    60 │   │   raise RuntimeError("Pages must be of type discord.Embed or str")            │
                    │    61 │   if not all(isinstance(x, discord.Embed) for x in pages) and not all(            │
                    │    62 │   │   isinstance(x, str) for x in pages                                           │
                    └───────────────────────────────────────────────────────────────────────────────────────────┘
                    IndexError: list index out of range

**Comment by brandons209** [comment] 2021-01-06 17:36
So reinstalling didn't fix it? I am not sure what to fix since I can't reproduce the issue. Like I said, its trying to create a menu but its not finding any guilds, something messed up. Try deleting the `settings.json` for the cog under your cogs folder in the RedBot data folder. Then restart the bot and see if that fixes it.

**Comment by brandons209** [comment] 2021-02-06 08:44
Closing this since no response for a month.

**Closed as completed** 2021-02-06 08:45 UTC
Labels: confession, Needs More Info
